---
title: "Partie 3 (V2) : Analyse de la production de la base Cultivation 2014"
format:
  html:
    toc: true
    theme: cosmo
editor: source
params:
  annee: 2011  # par défaut
---

```{r, message=FALSE, warning=FALSE}
rm(list = setdiff(ls(), "params"))
graphics.off()
cat("\014")
```

```{r, message=FALSE, warning=FALSE}
here::i_am("ICRESAT_database_analysis/Analyse_production_V2.qmd")
library(dplyr)
library(tidyr)
library(readxl)
library(ggplot2)
library(scales)
library(knitr)
library(tibble)
library(tidyverse)
library(gt)
```

```{r import_data}
Cultivation_expand_all <- readRDS(here::here("Base de données générées", "Cultivation_expand", "Cultivation_expand_all.rds"))

Cultivation_oper_all <- readRDS(here::here("Base de données générées", "Cultivation_oper", "Cultivation_oper_all.rds"))

Cultivation_plot_all <- readRDS(here::here("Base de données générées", "Cultivation_plot", "Cultivation_plot_all.rds"))

Cultivation_hh_all <- readRDS(here::here("Base de données générées", "Cultivation_hh", "Cultivation_hh_all.rds"))
```

********************************************************************************

Analyse de la base Cultivation_expand, pour l'année 2014

Cette base inclut les opérations non complétées (c’est-à-dire celles avec un temps de travail égal à 0), pour lesquelles on a ajouté des lignes, et les variables Caste et Caste_group. 

## Principales cultures

```{r Nombre de ménages, champs et cultures distincts}
n_menages <- Cultivation_hh_all |>
  distinct(VDS_ID) |>
  summarise(nb = n()) |>
  pull(nb)

n_champs <- Cultivation_plot_hh |>
  distinct(VDS_ID, SUB_PLOT_CODE) |>
  summarise(nb = n()) |>
  pull(nb)

n_crops <- Cultivation_plot_hh |>
  distinct(CROP) |>
  summarise(nb = n()) |>
  pull(nb)

cat("Nombre total de ménages :", n_menages, "\n")
cat("Nombre total de champs distincts :", n_champs, "\n")
cat("Nombre total de cultures :", n_crops, "\n")
```







